sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
  - '5'
  - '4'
before_install:
  - npm i -g npm@^2.0.0
install:
  - npm install -g coveralls
  - npm install
before_script:
  - npm prune
script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
